export class Exceptions {
    public static EXCEEDING_CONNECTION_ATTEMPTS = 'EXCEEDING_CONNECTION_ATTEMPTS';
    public static CONNECTION_NOT_ESTABLISHED = 'CONNECTION_NOT_ESTABLISHED';
    public static NOT_INITIALIZED = 'NOT_INITIALIZED';
    public static INVALID_MESSAGE_FORMAT = 'MESSAGE_SHOULD_BE_VALID_RECORD';
    public static UNSUPPORTED_SCHEMA = 'UNSUPPORTED_SCHEMA';
}