const RUNMQ_PREFIX = "_runmq_"
export const Constants = {
    ROUTER_EXCHANGE_NAME: RUNMQ_PREFIX + "router",
    DEAD_LETTER_ROUTER_EXCHANGE_NAME: RUNMQ_PREFIX + "dead_letter_router",
    RETRY_DELAY_QUEUE_PREFIX: RUNMQ_PREFIX + "retry_delay_",
    DLQ_QUEUE_PREFIX: RUNMQ_PREFIX + "dlq_",
}

export const DEFAULTS = {
    RECONNECT_DELAY: 5000,
    MAX_RECONNECT_ATTEMPTS: 5,
    PREFETCH_COUNT: 1,
    PROCESSING_ATTEMPTS: 1,
    PROCESSING_RETRY_DELAY: 1000,
}